name: vlm
channels:
  - defaults
  - nvidia
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - dbus=1.16.2=h5bd4931_0
  - expat=2.7.1=h6a678d5_0
  - fontconfig=2.15.0=h2c49b7f_0
  - freetype=2.13.3=h4a9f257_0
  - gds-tools=1.15.1.6=h2e68323_0
  - gmp=6.3.0=h6a678d5_0
  - icu=73.1=h6a678d5_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libcublas=13.1.0.3=hf83d1bd_0
  - libcublas-dev=13.1.0.3=hf83d1bd_0
  - libcublas-static=13.1.0.3=h3b4bcfc_0
  - libcufft=12.0.0.61=hf0c36ae_0
  - libcufft-dev=12.0.0.61=hf0c36ae_0
  - libcufft-static=12.0.0.61=h3b4bcfc_0
  - libcufile=1.15.1.6=h2e68323_0
  - libcufile-dev=1.15.1.6=h2e68323_0
  - libcufile-static=1.15.1.6=h3b4bcfc_0
  - libcurand=10.4.0.35=h50d9014_0
  - libcurand-dev=10.4.0.35=h50d9014_0
  - libcurand-static=10.4.0.35=h3b4bcfc_0
  - libcusolver=12.0.4.66=h3570045_0
  - libcusolver-dev=12.0.4.66=h3570045_0
  - libcusolver-static=12.0.4.66=h3b4bcfc_0
  - libcusparse=12.6.3.3=h8296a5b_0
  - libcusparse-dev=12.6.3.3=h8296a5b_0
  - libcusparse-static=12.6.3.3=h3b4bcfc_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libglib=2.84.4=h77a78f3_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libnpp=13.0.1.2=hfdad374_0
  - libnpp-dev=13.0.1.2=hfdad374_0
  - libnpp-static=13.0.1.2=hfdad374_0
  - libnsl=2.0.0=h5eee18b_0
  - libnvfatbin=13.0.85=hf384b4a_0
  - libnvfatbin-dev=13.0.85=hf384b4a_0
  - libnvfatbin-static=13.0.85=h3b4bcfc_0
  - libnvjitlink=13.0.88=hb0a779f_0
  - libnvjitlink-dev=13.0.88=hb0a779f_0
  - libnvjitlink-static=13.0.88=h3b4bcfc_0
  - libnvjpeg=13.0.1.86=h86e7e20_0
  - libnvjpeg-dev=13.0.1.86=hbc2eedf_0
  - libnvjpeg-static=13.0.1.86=0
  - libnvvm-samples=12.1.105=0
  - libpng=1.6.50=h2ed474d_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.8=hfdd30dd_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - nsight-compute=2025.3.1.4=hcd14d4a_0
  - nspr=4.37=h8459abe_0
  - nss=3.117=h3135ca0_0
  - ocl-icd=2.3.2=h5eee18b_1
  - openssl=3.0.18=hd6dcaed_0
  - pcre2=10.46=hf426167_0
  - pip=25.2=pyhc872135_1
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.19=h6fa692b_0
  - readline=8.3=hc2a1206_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py310h06a4308_0
  - xkeyboard-config=2.44=h5eee18b_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - addict==2.4.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.1
      - aiosignal==1.4.0
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - annotated-doc==0.0.3
      - annotated-types==0.7.0
      - anyio==4.11.0
      - asgiref==3.10.0
      - async-timeout==4.0.3
      - attrs==25.4.0
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.0
      - colorama==0.4.6
      - contourpy==1.3.2
      - crcmod==1.7
      - cryptography==46.0.3
      - cycler==0.12.1
      - cython==3.1.6
      - dataclasses-json==0.6.7
      - distro==1.9.0
      - django==5.2.7
      - dotenv==0.9.9
      - exceptiongroup==1.3.0
      - fastapi==0.120.0
      - filelock==3.14.0
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - greenlet==3.2.4
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - httpx-sse==0.4.3
      - idna==3.11
      - jinja2==3.1.6
      - jiter==0.11.1
      - jmespath==0.10.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - kiwisolver==1.4.9
      - langchain==0.2.17
      - langchain-classic==1.0.0
      - langchain-community==0.4
      - langchain-core==0.2.43
      - langchain-openai==0.1.25
      - langchain-text-splitters==1.0.0
      - langsmith==0.1.147
      - markdown==3.9
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - marshmallow==3.26.1
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - mmcv==2.2.0
      - mmdet==3.3.0
      - mmengine==0.10.7
      - mmpose==1.3.2
      - model-index==0.1.11
      - mpmath==1.3.0
      - multidict==6.7.0
      - munkres==1.1.4
      - mypy-extensions==1.1.0
      - networkx==3.3
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - openai==1.109.1
      - opencv-python==4.12.0.88
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.1.3
      - ordered-set==4.1.0
      - orjson==3.11.4
      - oss2==2.17.0
      - packaging==24.2
      - pandas==2.3.3
      - pillow==11.3.0
      - platformdirs==4.5.0
      - propcache==0.4.1
      - pycocotools==2.0.10
      - pycparser==2.23
      - pycryptodome==3.23.0
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pydantic-settings==2.11.0
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - pytz==2023.4
      - pyyaml==6.0.3
      - regex==2025.10.23
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rich==13.4.2
      - scipy==1.15.3
      - setuptools==60.2.0
      - shapely==2.1.2
      - six==1.17.0
      - sniffio==1.3.1
      - sqlalchemy==2.0.44
      - sqlparse==0.5.3
      - starlette==0.48.0
      - sympy==1.13.1
      - tabulate==0.9.0
      - tenacity==8.5.0
      - termcolor==3.1.0
      - terminaltables==3.1.10
      - tiktoken==0.12.0
      - tomli==2.3.0
      - torch==2.3.0+cu121
      - torchaudio==2.3.0+cu121
      - torchvision==0.18.0+cu121
      - tqdm==4.65.2
      - triton==2.3.0
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==1.26.20
      - uvicorn==0.38.0
      - xtcocotools==1.14.3
      - yapf==0.43.0
      - yarl==1.22.0
      - zstandard==0.25.0
prefix: /home/team16/anaconda3/envs/vlm
