name: Android Instrumentation Coverage

on:
  push:
    branches: [ "iteration-final-test" ]
  pull_request:

jobs:
  android-test-coverage:
    runs-on: ubuntu-latest

    steps:
      # 1. 체크아웃
      - name: Checkout
        uses: actions/checkout@v4

      # 2. JDK 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3. Gradle 캐시
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # 4. Android SDK 설치
      - name: Install Android SDK
        run: sdkmanager --install "system-images;android-33;google-atd;arm64-v8a"
      


      # 5. Managed Device Coverage 실행
      - name: Run Instrumentation Coverage
        run: ./gradlew :app:pixel6DebugAndroidTestCoverage
        working-directory: android-studio-app
      # 6. 커버리지 리포트 아티팩트 업로드
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: android-studio-app/app/build/reports/androidTests/managedDevice/coverage/
