name: Android Coverage Report

on:
  workflow_dispatch: # 수동 실행
  push:
    branches: [ "iteration-final-test" ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: android-studio-app
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Upload coverage.ec
        uses: actions/upload-artifact@v4
        with:
          name: coverage-ec
          path: '**/coverage.ec'
      - name: Download coverage.ec
        uses: actions/download-artifact@v4
        with:
          name: coverage-ec
          path: app/
      - name: Check Jacoco report
        run: ls -R ./

          
      # 이미 instrumentation test를 통해 .ec 파일이 생성되어 있다고 가정
      # 여기서는 리포트만 생성
      - name: Generate Jacoco coverage report
        run: ./gradlew pixel6DebugAndroidTestCoverage --rerun-tasks
      - name: Check Jacoco report
        run: ls -R ./
      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: app/build/reports/
      - name: Upload problem report artifact
        uses: actions/upload-artifact@v4
        with:
          name: problem-report
          path: app/build/
